### ISSUE TITLE
Add support for preset default taglist

### ISSUE THREAD

**Issue by amreo** [amreo/ercole-services#46]
**Is your feature request related to a problem? Please describe.**
I don't want to write every time the same tag.  

**Describe the solution you'd like**
I want to have the possibility do get a set of default tags

**Describe alternatives you've considered**
To write every time the same tag or copy-pasting

**Additional context**
POST /hosts/{hostname}/databases/{dbname}/tags/

**Comment by cirelli94** [comment]
preset default taglist should be set in config.json?

**Comment by raffaelloferrari** [comment]
No, preset tag should be set in a configuration page.

**Comment by cirelli94** [comment]
@raffaelloferrari the idea is to implement this issue using config.json, then move the configuration in a more correct place while solving #48
