### ISSUE TITLE
Add support for reading multiple configuration files in /etc/ercole.d/

### ISSUE THREAD

**Issue by amreo** [amreo/ercole-services#61]
**Describe the solution you'd like**
I want that every file in `/etc/ercole.d/*.toml` in `sort -n` order are read.

**Comment by cirelli94** [comment]
In what order compared to others?

less priority
```
		"/opt/ercole/config.toml",
		"/usr/share/ercole/config.toml",
		"/etc/ercole.toml",
		home + "/.ercole.toml",
		"config.toml",
		extraConfigFile //passed by -c
```
top priority

**Comment by amreo** [comment]
After "/etc/ercole.toml", before home + "/.ercole.toml",
