### ISSUE TITLE
Setup  https://sonarcloud.io/ for the project

### ISSUE THREAD

**Issue by amreo** [amreo/ercole-services#66]
**Is your feature request related to a problem? Please describe.**
I want to know how well the project is written

**Describe the solution you'd like**
I want that sonar scan the project every time travis build the project

**Comment by amreo** [comment]
https://sonarcloud.io/dashboard?id=amreo_ercole-services

I don't find the correct badge to use.
https://shields.io/category/analysis

**Comment by cirelli94** [comment]
Just search for sonar, there are several
